### ISSUE TITLE
How to setup correctly?

### ISSUE THREAD

**Issue by gunchu** [joachimneu/pelican-md-metayaml#1]
Thanks for the plugin! I want to try it out, but facing problem setting it up!

Can you please mention all the dependencies that need to be installed? I had to install 'Markdown', 'pyyaml' (obvious now, but README didn't mention this :-|)

Still getting this error on running Pelican:
'NoneType' object is not iterable

**Comment by deragon** [comment]
I have the same problem.  Version 2.5.2.  Here is the stacktrace:

ERROR: Could not process pages/linux/ubuntu/bugs/2015-01-01-ubuntu-bug-XXX-Test.markdown
  | 'NoneType' object is not iterable
  |___
  | Traceback (most recent call last):
  |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/generators.py", line 629, in generate_context
  |     context_sender=self)
  |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/readers.py", line 459, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/sp/home/hans/Seafile/Hans/Personnel/websites/plugins/pelican-plugins/md_yaml/md_yaml.py", line 40, in read
  |     self._md = Markdown(extensions=self.extensions)
  |   File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 154, in __init__
  |     configs=kwargs.get('extension_configs', {}))
  |   File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 180, in registerExtensions
  |     ext = self.build_extension(ext, configs.get(ext, {}))
  |   File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 265, in build_extension
  |     return module.makeExtension(**configs)
  |   File "/sp/home/hans/Seafile/Hans/Personnel/websites/plugins/pelican-plugins/md_yaml/mdx_meta_yaml/__init__.py", line 8, in makeExtension
  |     return MetaYamlExtension(configs=configs)
  |   File "/usr/local/lib/python2.7/dist-packages/markdown/extensions/__init__.py", line 36, in __init__
  |     self.setConfigs(kwargs.pop('configs', {}))
  |   File "/usr/local/lib/python2.7/dist-packages/markdown/extensions/__init__.py", line 75, in setConfigs
  |     for key, value in items:
  | TypeError: 'NoneType' object is not iterable

**Comment by deragon** [comment]
I just realized the issue has been closed.  I will open a new one.
