### ISSUE TITLE
AttributeError: 'str' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by deragon** [joachimneu/pelican-md-metayaml#4]
Whenever I enable the md-yaml plugin and configure a page with YAML metadata, I get the following error:

    DEBUG: Read file pages/linux/ubuntu/bugs/2015-01-01-ubuntu-bug-XXX-Test.markdown -> Page
    ERROR: Could not process pages/linux/ubuntu/bugs/2015-01-01-ubuntu-bug-XXX-Test.markdown
      | 'str' object has no attribute 'tzinfo'
      |___
      | Traceback (most recent call last):
      |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/generators.py", line 629, in generate_context
      |     context_sender=self)
      |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/readers.py", line 492, in read_file
      |     context=context)
      |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/contents.py", line 126, in __init__
      |     self.date = set_date_tzinfo(self.date, timezone)
      |   File "/sp/seafile/software/nodist/noarch/src/pelican/pelican/utils.py", line 581, in set_date_tzinfo
      |     if tz_name and not d.tzinfo:
      | AttributeError: 'str' object has no attribute 'tzinfo'

Even though the stacktrace does not show any code related to md-yaml, since it only occurs when I have the following configured in pelicanconf.py and a page making use of YAML metadata:

PLUGINS = ['md_yaml']

Beside, the stacktrace does show that readers.py is involved.  Probably the YAML reader left something behind after being called that causes the problem.

In my pelicanconf.py, I have also the following configured:

TIMEZONE = 'America/Montreal'

I am running the latest version of md-yaml from git and Pelican 3.5.0.

**Comment by nfarrar** [comment]
I'm having the same issue.

**Comment by joachimneu** [comment]
I'm sorry guys, that I can't find time in these days to work on this issue. Maybe this repository works better for you? https://github.com/pR0Ps/pelican-md-metayaml

**Comment by nfarrar** [comment]
Np. That one does work. :) Thanks!
