### ISSUE TITLE
Naming Convention/Organization is Nonstandard, breaks most Use Cases

### ISSUE THREAD

**Issue by nfarrar** [joachimneu/pelican-md-metayaml#6]
Hey, I just saw you're fork got pushed to the main repo. I've been using my own fork of it [here](https://github.com/nfarrar/pelican-md-metayaml):

The way you've got you're repository organized breaks the typical use cases, for example:

    git submodule add https://github.com/getpelican/pelican-plugins
    git submodule update --init --recursive

And in pelicanconf.py:

    PLUGIN_PATHS = [
        'plugins/pelican-plugins',
    ]
    PLUGINS = [ 'gravatar', 'sitemap', 'summary', 'md_metayaml'  ]

Then when you attempt to build:

    make html
    ERROR: Cannot load plugin `md_metayaml`
      | No module named md_metayaml

Pelican can't import it because the repository is named pelican-md_metayaml, while the plugin itself is md_metayaml. The easy fix is to rename pelican-md_metayaml to md_metayaml, but then we have to fork the entire pelican-plugins repo :(

The layout also prevents users from adding it as a separate path:

     PLUGIN_PATHS = [
        'plugins/pelican-plugins',
        'plugins/pelican-plugins/pelican-md_metayaml'
    ]
 
    make html

    Traceback (most recent call last):
     File "plugins/pelican-plugins/pelican-md_metayaml/md_metayaml.py", line 4, in <module>
       from .markdown_metayaml.meta_yaml import MetaYamlExtension
       ValueError: Attempted relative import in non-package

This import error can be fixed by moving all the code into a single package, as some of the other plugins have done. But again, then we have to fork our modified copy of the entire pelican-plugins repo. The layout also breaks another use-case:

    git submodule add https://github.com/getpelican/pelican-plugins plugins/pelican-plugins
    git submodule add https://github.com/joachimneu/pelican-md-metayaml.git/pelican-md-metayaml
    git submodule update --init --recursive
    PLUGIN_PATHS = [
        'plugins/pelican-plugins',
        'plugins/pelican-md_metayaml'
    ]
    PLUGINS = [ 'gravatar', 'sitemap', 'summary', 'md_metayaml'  ]

Essentially, just trying to store the plugins in the same directory. Because pelican-md_metayaml isn't packaged, you need to add the parent directory to PLUGIN_PATHS, i.e.: 

    PLUGIN_PATHS = [
        'plugins/pelican-plugins',
        'plugins' # the parent directory of pelican-md_metayaml
    ]

But now the plugin paths overlap and it breaks the plugin system - so you have to clone the git repository into a nested directory, i.e.: 

    git submodule add https://github.com/getpelican/pelican-plugins plugins/pelican-plugins
    git submodule add https://github.com/joachimneu/pelican-md-metayaml.git/pelican-md-metayaml/md_metayaml
    git submodule update --init --recursive
    PLUGIN_PATHS = [
        'plugins/pelican-plugins',
        'plugins/pelican-md_metayaml'
    ]
    PLUGINS = [ 'gravatar', 'sitemap', 'summary', 'md_metayaml'  ]

And now it will work. This gets pretty confusing for anyone trying to use the code if they don't understand python imports very well, so I'd recommend fixing the layout so it works with common scenarios. :)

**Comment by chriskrycho** [comment]
:+1: This was perplexing me, too!

**Comment by joachimneu** [comment]
Thank you for your detailed bug report, this problem should be fixed now with the latest changes. :) I updated the documentation accordingly.
