### ISSUE TITLE
Date without time breaks parser

### ISSUE THREAD

**Issue by nfarrar** [joachimneu/pelican-md-metayaml#7]
If you specify a date (works with the standard pelican parser) as:

    ---
    Date: 2015-02-20
    ---

... the parser breaks. I took a quick look at the code, but didn't an obvious solution.

**Comment by ashander** [comment]
`Markdown` returns `Meta` as a dict where "keys are all lowercase and the values consist of a list of strings where each item is one line for that key"

But, in the extension used in this reader, dates without time specified become  `datetime.date`

``` py
text_ld ='''---
title: Yaml post
date: 2015-04-25 10:20
...
'''

text_sd ='''---
title: Yaml post
date: 2015-04-25
...
'''

import markdown
from meta_yaml import MetaYamlExtension

md = markdown.Markdown(extensions=['meta', MetaYamlExtension()])

md.convert(text_ld)
md.Meta
# {'date': ['2015-04-25 10:20'], 'title': ['Yaml post']}
md.convert(text_sd)
md.Meta
# {'date': [datetime.date(2015, 4, 25)], 'title': ['Yaml post']}
```

**Comment by ashander** [comment]
Ultimately due to use of `yaml.load` on line 98 of `meta_yaml.py`:

``` py
import yaml
from yaml import CSafeLoader as Loader
yaml.load("\n".join(['date: 2015-04-25 10:40']), Loader)
# {'date': '2015-04-25 10:40'}

yaml.load("\n".join(['date: 2015-04-25']), Loader)
# {'date': datetime.date(2015, 4, 25)}
```

**Comment by ashander** [comment]
Seems like using `BaseLoader` will avoid this issue -- I created a PR in the yaml metadata extension repo

**Comment by joachimneu** [comment]
Thank you for your contributions! :) I think this issue is fixed now with the latest changes, right? (If not, please re-open/file a new bug report.)

**Comment by ashander** [comment]
Thanks!

Yes, it works for me with  teoric:master version of yam_metadata, since https://github.com/teoric/python-markdown-yaml-meta-data/pull/4 was merged.
